directories:
  output: release
  buildResources: resources
appId: br.com.gclocamoto.app
productName: GC Locamoto
copyright: Copyright © 2026 GC Locamoto
icon: resources/icon.ico
files:
  - filter:
      - dist/electron/**/*
      - dist/database/**/*
      - out/**/*
      - database/migrations/sqlite/**/*
      - node_modules/**/*
      - package.json
      - .env*
npmRebuild: true
asarUnpack:
  - node_modules/better-sqlite3/**/*
  - node_modules/bindings/**/*
win:
  target:
    - target: nsis
      arch:
        - x64
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
electronVersion: 34.5.8
